apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-local-tls
  namespace: kube-system
spec:
  secretName: wildcard-local-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.local"
    - "local"
