apiVersion: v1
kind: Service
metadata:
  name: fm-compta-consulting-backend
  namespace: default
spec:
  selector:
    app: fm-compta-consulting-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
