apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fm-compta-consulting-tls
  namespace: default
spec:
  secretName: fm-compta-consulting-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - fm-compta-consulting.local
