apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-scripts
  namespace: default
data:
  01-create-collections.js: |
    // Création des collections
    db = db.getSiblingDB('compta_db');

    // Création de la collection Users si elle n'existe pas
    if (!db.getCollectionNames().includes('users')) {
      db.createCollection('users');
      
      // Création d'un utilisateur administrateur par défaut
      db.users.insertOne({
        name: "Felicia MITITELU",
        email: "felicia@fmcompta.be",
        password: "$2a$12$ItMLSMNr/TRMVhxtjXEoFu7nYxumTVl6Sc9Tc68ln7duVLLefljqO", // Felicica89 hashé
        role: "admin",
        createdAt: new Date(),
        updatedAt: new Date()
      });
      
      print("Collection 'users' créée avec l'administrateur par défaut");
    }

    // Création de la collection Appointments si elle n'existe pas
    if (!db.getCollectionNames().includes('appointments')) {
      db.createCollection('appointments');
      print("Collection 'appointments' créée");
    }

    // Création des index
    db.users.createIndex({ email: 1 }, { unique: true });
    db.users.createIndex({ role: 1 });

    db.appointments.createIndex({ userId: 1 });
    db.appointments.createIndex({ date: 1 });
    db.appointments.createIndex({ status: 1 });
    db.appointments.createIndex({ userId: 1, date: 1 });

    print("Initialisation de la base de données terminée");
  02-ensure-admin.js: |
    // S'assurer que l'utilisateur administrateur existe
    db = db.getSiblingDB("compta_db");

    // remove old admin
    db.users.deleteOne({ email: "felicia@fmcompta.be" });

    // Rechercher l'administrateur par son email
    const adminExists = db.users.findOne({ email: "admin@fmcompta.be" });

    // Si l'administrateur n'existe pas, le créer
    if (!adminExists) {
      print("Création du compte administrateur...");

      db.users.insertOne({
        name: "Admin",
        email: "admin@fmcompta.be",
        password: "$2a$10$3Hsp0C5pjCVoP9d6ji1ebeswqawTaZmROiXoysDs9KqvbiP7.BWya", // admin123 hashé
        role: "admin",
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      print("Compte administrateur créé avec succès");
    } else {
      print("Le compte administrateur existe déjà");
    }

    // S'assurer que le rôle est bien 'admin'
    db.users.updateOne(
      { email: "admin@fmcompta.be" },
      {
        $set: {
          role: "admin",
          password: "$2a$10$3Hsp0C5pjCVoP9d6ji1ebeswqawTaZmROiXoysDs9KqvbiP7.BWya", // S'assurer que le mot de passe est à jour
        },
      },
    );

    print("Le compte administrateur est configuré correctement");