apiVersion: v1
kind: Service
metadata:
  name: fm-compta-consulting-frontend
  namespace: default
spec:
  selector:
    app: fm-compta-consulting-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
