apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-tls
  namespace: sonarqube
spec:
  secretName: sonarqube-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: sonarqube.local
  dnsNames:
  - sonarqube.local