apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-tls
  namespace: sonarqube
spec:
  secretName: sonarqube-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - sonarqube.local
