apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zap-tls
  namespace: owasp
spec:
  secretName: zap-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - zap.local
