---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: fm-compta-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: rolandsebastien/testops
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      labels:
        - self-hosted
        - kubernetes
        - linux
        - x64
      hostAliases:
        - ip: "192.168.2.9"
          hostnames:
            - registry.local
            - registry-ui.local
            - argocd.local
            - grafana.local
            - longhorn.local
            - prometheus.local
            - dashboard.local
            - fm-compta-consulting.local
            - sonarqube.local
            - allure.local
      containers:
        - name: runner
          image: summerwind/actions-runner-dind
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          resources:
            requests:
              cpu: "2"
              memory: "3Gi"
            limits:
              cpu: "4"
              memory: "6Gi"
        - name: dind
          image: docker:dind
          args:
            - --insecure-registry=registry.local
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: fm-compta-runner-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: fm-compta-runner
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - rolandsebastien/testops
