---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: fm-compta-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: rolandsebastien/testops
      ephemeral: false
      dockerdWithinRunnerContainer: true
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      labels:
        - self-hosted
        - kubernetes
        - linux
        - x64
      hostAliases:
        - ip: "__INGRESS_IP__"
          hostnames:
            - registry.local
            - registry-ui.local
            - argocd.local
            - grafana.local
            - longhorn.local
            - prometheus.local
            - dashboard.local
            - fm-compta-consulting.local
            - sonarqube.local
            - allure.local
      image: summerwind/actions-runner-dind:ubuntu-22.04
      dockerRegistryMirror: ""
      dockerdContainerResources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: fm-compta-runner-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: fm-compta-runner
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - rolandsebastien/testops
