apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: allure-route
  namespace: allure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`allure.local`)
      kind: Rule
      services:
        - name: allure
          port: 5050
  tls:
    secretName: allure-tls-secret
