apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allure
  namespace: allure
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - allure.local
    secretName: allure-tls
  rules:
  - host: allure.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: allure
            port:
              number: 5050