apiVersion: v1
kind: Service
metadata:
  name: allure
  namespace: allure
spec:
  selector:
    app: allure
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      name: api
    - port: 5252
      targetPort: 5252
      name: web-ui
  type: ClusterIP
